apiVersion: v1
kind: Pod
metadata:
  name: sample-annotations
  annotations:
    annotation1: value1
    annotation2: value2
spec:
  containers:
    - name: nginx-container
      image: nginx:1.13
      ports:
        - containerPort: 80
